#!/usr/bin/env bash
# This script configures an loadBalancer
sudo apt-get update
apt-get install -y haproxy=1.6.\*
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver web1  check\n\tserver web2  check\n" >> /etc/haproxy/haproxy.cfg
