#!/usr/bin/env bash
# This script displays numbers from 1 to 20
# Displays "bad luck from China" on the 4th iteration
# Displays "bad luck from Japan" on the 9th iteration
# Displays "bad luck from Italy" on the 17th iteration
i=1

while [ $i -le 20 ]
do
	case "$i" in
	
	4)
		echo "$i"
		echo "bad luck from China"
		;;

	9)
		echo "$i"
		echo "bad luck from Japan"
		;;
	
	17)
		echo "$i"
		echo "bad luck from Italy"
		;;
	*)
		echo "$i"
	esac
	((i++))
done
